<Project Sdk="Microsoft.NET.Sdk" InitialTargets="CheckPaths">
  <Import Project="Paths.props" />

  <PropertyGroup>
    <AssemblyName>UKMDUnlocker</AssemblyName>
    <Description>Adds ULTRAKILL MUST DIE to the difficulty selection menu.</Description>
    <RepositoryUrl>https://github.com/Bryan-000/UKMDUnlocker</RepositoryUrl>
    <Version>0.4.0</Version>

    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>14</LangVersion>
    <DebugType>embedded</DebugType>
    <RootNamespace>UKMDUnlocker</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>IDE1006, IDE0044, IDE0130, IDE0028</NoWarn>

    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <ManagedPath>$(ULTRAKILLPath)\ULTRAKILL_Data\Managed</ManagedPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HarmonyX" Version="2.9.0"/>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.29" IncludeAssets="compile" />

    <Reference Include="$(ManagedPath)\plog.dll" />
    <Reference Include="$(ManagedPath)\Assembly-CSharp.dll" />
    <Reference Include="$(ManagedPath)\Unity.TextMeshPro.dll" />
    <Reference Include="$(ManagedPath)\UnityEngine.UI.dll" />

    <Reference Include="$(PConfigPath)\PluginConfigurator.dll" />
    <Reference Include="$(ALLPath)\AngryUiComponents.dll" />
    <Reference Include="$(ALLPath)\AngryLevelLoader.dll" Publicize="true" />
  </ItemGroup>

  <!-- Checks required paths for building to see if they exist, if they dont it throws an error. -->
  <Target Name="CheckPaths">
    <Error Condition="!Exists('$(%(PathsToCheck.Identity))')"
           Text="%(PathsToCheck.Identity) path does not exist. Open the Paths.props file and set %(PathsToCheck.Identity) to where ever your %(PathsToCheck.Name) install is." />
  </Target>

  <Target Name="CopyDLLs" AfterTargets="Build">
    <!-- Copy the DLL to all the m_CopyPaths -->
    <Message Text="Copying DLL to %(m_CopyPaths.Identity)..." Importance="high" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="%(m_CopyPaths.Identity)" OverwriteReadOnlyFiles="true"  SkipUnchangedFiles="true" />
  </Target>
</Project>